### ISSUE TITLE
Interactive map?

### ISSUE THREAD

**Issue by fabswt** [stcoats/YouTube_Speech_Rate#1]
Hi!
I'm not sure if this is the best place to ask, and so feel free to delete this thread if not.

I was wondering if you, the author, or anyone else, had taken it upon themselves to produce an interactive map based on the data? (`YouTube_Channels.csv`)

Thanks for the heads-up,
Fabien

**Comment by stcoats** [comment]
Hello Fabien, thanks for your question. Sorry for the delay in responding. I have created some interactive maps based on this data: the main one is https://stcoats.github.io/artic_rate_new.html, and the corresponding article is https://journals.sagepub.com/doi/10.1177/0023830919894720. The self-archived version is available at http://cc.oulu.fi/~scoats/Articulation_Rate_in_American_English_LAS_revised_v2_Author_Version.pdf. 

All the best, 
Steven
